vim.keymap.set("n", "<esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<C-b>", "<cmd>Neotree toggle<CR>", { remap = true, silent = true })
vim.keymap.set({ "n", "x", "o" }, "<Leader>/", "gcc", { remap = true })
vim.keymap.set("n", "<leader>o", "<cmd>Neotree focus<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-s>", "<cmd>silent! update | redraw<CR>", { noremap = true, silent = true })
vim.keymap.set({ "i", "x" }, "<C-s>", "<ESC><cmd>silent! update | redraw<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>h", "<cmd>bprev<CR>", { remap = true })
vim.keymap.set("n", "<leader>l", "<cmd>bnext<CR>", { remap = true })
