vim.keymap.set("n", "<esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<C-b>", function()
	MiniFiles.open()
end, { remap = true, silent = true })
vim.keymap.set({ "n", "x", "o" }, "<Leader>/", "gcc", { remap = true })
vim.keymap.set("n", "<C-s>", "<cmd>silent! update | redraw<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "gc", "<nop>")
vim.keymap.set({ "i", "x" }, "<C-s>", "<ESC><cmd>silent! update | redraw<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>h", "<cmd>bprev<CR>", { remap = true })
vim.keymap.set("n", "<leader>l", "<cmd>bnext<CR>", { remap = true })
vim.keymap.set("n", "<leader>c", "<cmd>bdelete<CR>", { noremap = true })
vim.keymap.set("n", "<leader>f", "<cmd>Telescope find_files<CR>", { remap = true })
vim.keymap.set("n", "<leader><leader>", "<cmd>Telescope live_grep<CR>", { remap = true })
vim.keymap.set("n", "<leader>r", "<cmd>Telescope frecency<CR>", { remap = true })
