vim.keymap.set("n", " <esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<C-b>", "<cmd>Neotree toggle<CR>", { remap = true, silent = true })
vim.keymap.set({ "n", "x", "o" }, "<Leader>/", "gcc", { remap = true })
vim.keymap.set("n", "<leader>o", "<cmd>Neotree focus<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-s>", "<cmd>update<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("i", "<C-s>", "<ESC>:update<CR>", { noremap = true, silent = true })
