local opt = vim.opt

opt.clipboard = "unnamedplus" -- Sync with system clipboard
opt.copyindent = true
opt.confirm = true -- Confirm to save changes before exiting modified buffer
opt.cursorline = false -- Disable highlighting of the current line
opt.expandtab = true -- Use spaces instead of tabs
opt.cmdheight = 0
opt.ignorecase = true -- Ignore case
opt.incsearch = true
opt.infercase = true
opt.smartcase = true -- Don't ignore case with capitals
opt.inccommand = "nosplit" -- preview incremental substitute
opt.laststatus = 3 -- global statusline
opt.mouse = "a" -- Enable mouse mode
opt.mousemoveevent = true
opt.number = true -- Print line number
opt.relativenumber = true -- Relative line numbers
opt.shiftround = true -- Round indent
opt.shiftwidth = 4
opt.softtabstop = 4
opt.shortmess:append("WIcCq") -- Silence
opt.showmode = false -- Dont show mode since we have a statusline
opt.signcolumn = "number" -- Always show the signcolumn, otherwise it would shift the text each time
opt.smartindent = true -- Insert indents automatically
opt.splitbelow = true -- Put new windows below current
opt.splitkeep = "screen"
opt.splitright = true -- Put new windows right of current
opt.tabstop = 4 -- Number of spaces tabs count for
opt.termguicolors = true -- True color support
opt.timeoutlen = 300
opt.undofile = true
opt.backup = false
opt.writebackup = false
opt.breakindent = true
opt.linebreak = true
opt.undolevels = 2000
opt.updatetime = 200 -- Save swap file and trigger CursorHold
opt.virtualedit = "block" -- Allow cursor to move where there is no text in visual block mode
opt.wrap = false -- Disable line wrap
opt.smoothscroll = true
opt.pumheight = 10
vim.cmd("autocmd FileType * set formatoptions-=ro")
